version: '3'
services:
  selenium-hub:
    image: selenium/hub
    logging:
      driver: 'none'

  node-chrome:
    image: selenium/node-chrome
    logging:
      driver: 'none'
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  node-firefox:
    image: selenium/node-firefox
    logging:
      driver: 'none'
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  test-machine:
    build:
      context: .
    depends_on:
      - selenium-hub
      - node-chrome
      - node-firefox
